### ISSUE TITLE
Hi, great job! Is it ready yet? Also i've now switched to packet mode in V3

### ISSUE THREAD

**Issue by mofosyne** [lukasklinger/GameBoyPrinterReceiver#1]
Just discovered your project. Haven't tested if it still works, but nice job anyway! I'll make note to add it to the showcase if it's ready. https://github.com/mofosyne/arduino-gameboy-printer-emulator/issues/47

Just note that I'm now forcing everyone to use the raw packet output mode by default in V3 and just doing all the processing of the packet in javascript.

This is to allow for compatibility with games that uses compression. (e.g. premade high rez images in rom), plus its the preferred output now of a few other devs that requested this mode instead.

You may want to point users to V2 or V1 if you are not using raw packet decoding.

**Comment by mofosyne** [comment]
To make your life easier, refer to https://github.com/mofosyne/GameboyPrinterSniffer/tree/master/RealCapture for a few packet mode captures

**Comment by mofosyne** [comment]
Oh and join us at 

https://t.me/GameboyCamera

**Comment by lukasklinger** [comment]
Hi Brian, yes this is basically done and ready to use, at least for the Gameboy Camera :)
I will take a look at your v3 update this weekend and make changes where necessary!
Lukas
